---

- name: Cowrie | Install Output MySQL dependencies
  apt:
    name: "{{ item }}"
  become: True
  with_items:
    - "{{ cowrie_output_mysql_apt_dependencies }}"


- name: Cowrie | Create cowrie database
  mysql_db:
    state: present
    name: "{{ cowrie_output_mysql_database }}"
  become: True

- name: Cowrie | Add database user
  mysql_user:
    name: "{{ cowrie_output_mysql_username }}"
    password: "{{ cowrie_output_mysql_password }}"
    encrypted: no
    priv: "{{ cowrie_output_mysql_database }}.*:ALL"
    state: present
  become: True

- name: Cowrie | Import database scheme
  mysql_db:
    name: "{{ cowrie_output_mysql_database }}"
    state: import
    target: "{{ cowrie_directory}}/doc/sql/mysql.sql"
    login_user: "{{ cowrie_output_mysql_username }}"
    login_password: "{{ cowrie_output_mysql_password }}"
  ignore_errors: yes

- name: Cowrie | Set ACL for tty logs and www-data user
  acl:
    name: "{{ cowrie_directory }}/log/tty"
    entity: www-data
    etype: group
    permissions: rx
    recursive: yes
    state: present
  become: True

- pip:
    name: mysqlclient
    virtualenv: "{{ cowrie_directory }}/cowrie-env"
  become: True
