---
# tasks file for cowrie
- name: Cowrie | Install dependencies
  apt:
    name: "{{ item }}"
  become: True
  with_items:
    - "{{ cowrie_apt_dependencies }}"

- name: Cowrie | Check if cowrie cwd exists already
  stat:
    path: "{{ cowrie_directory }}"
  register: cowrie_cwd_exists

- name: Cowrie | Check if cowrie exists
  stat:
    path: "{{ cowrie_directory }}/setup.py"
  register: cowrie_exists

- name: Cowrie | Delete cowrie_cwd
  file:
    state: absent
    path: "{{ cowrie_directory }}"
  when: cowrie_cwd_exists.stat.exists is defined and cowrie_cwd_exists.stat.exists
          and cowrie_exists.stat.exists is defined and cowrie_exists.stat.exists == False

- name: Cowrie | Clone cowrie repository
  git:
    repo: https://github.com/micheloosterhof/cowrie.git
    dest: "{{ cowrie_directory }}"
    force: yes
  when: cowrie_exists.stat.exists is defined and cowrie_exists.stat.exists == False

- name: Cowrie | Generate password
  shell: date | md5sum | awk '{print $1; }'
  register: cowrie_password
  changed_when: False

- name: Cowrie | Create cowrie user
  user:
    name: cowrie
    home: "{{ cowrie_directory }}"
    password: "{{ cowrie_password.stdout }}"
    update_password: on_create
  become: True



#- name: Cowrie | Clone cowrie repository
#  shell: git clone https://github.com/micheloosterhof/cowrie.git /opt/cowrie
#  become: True
#  when: cowrie_exists.stat.exists == False

- name: Cowrie | Set directory owner
  file:
    path: "{{ cowrie_directory }}"
    owner: cowrie
    group: cowrie
    recurse: yes
    state: directory
  become: True

- name: Cowrie | Create virtualenv
  pip:
    virtualenv = "{{ cowrie_directory }}/cowrie-env"
    requirements="{{ cowrie_directory}}/requirements.txt"
  become: True
  become_user: cowrie
