---
# tasks file for cowrie
- name: Cowrie | Install dependencies
  apt:
    name: "{{ item }}"
  become: True
  with_items:
    - "{{ cowrie_apt_dependencies }}"

- name: Cowrie | Generate password
  shell: date | md5sum | awk '{print $1; }'
  register: cowrie_password

- name: Cowrie | Create cowrie user
  user:
    name: cowrie
    home: "{{ cowrie_directory }}"
    password: "{{ cowrie_password.stdout }}"
  become: True

- name: Cowrie | Check if cowrie exists already
  stat:
    path: "{{ cowrie_directory }}/setup.py"
  register: cowrie_exists

- name: Cowrie | Clone cowrie repository
  shell: git clone https://github.com/micheloosterhof/cowrie.git /opt/cowrie
  become: True
  when: cowrie_exists.stat.exists == False

- name: Cowrie | Set directory owner
  file:
    path: "{{ cowrie_directory }}"
    owner: cowrie
    group: cowrie
    recurse: yes
    state: directory
  become: True

- name: Cowrie | Create virtualenv
  pip:
    virtualenv = "{{ cowrie_directory }}/cowrie-env"
    requirements="{{ cowrie_directory}}/requirements.txt"
