---
# handlers file for cowrie

- name: iptables_save
  shell: iptables-save > /etc/iptables-rules
  become: True

- name: restart iptables-persistent
  service:
    name: netfilter-persistent
    state: restarted
  become: True
