---
# handlers file for cowrie

- name: iptables_save
  shell: iptables-save > /etc/iptables/rules.v4
  become: True

#- name: restart iptables-persistent
#  service:
#    name: netfilter-persistent
#    state: restarted
#  become: True

- name: restart iptables-persistent
  shell: >
    sleep 5s && service netfilter-persistent restart
  become: True
  async: 10
  poll: 0
